### ISSUE TITLE
border-image support for IE10?

### ISSUE THREAD

**Issue by AaronVanGeffen** [lojjic/PIE#264]
While most of CSS3PIE's feature aren't needed anymore in IE10, border-image is among the features that are still unsupported natively in IE10. Are there plans to support IE10 in this respect?

**Comment by bcjordan** [comment]
@lojjic that thread mentions one approach being making a version for IE10 that:

> includes only border-image support and tries to work around those disadvantages using modern APIs.

Do you have any pointers on where one might start implementing such support? What parts of the IE9 approach do not work in IE10? (or are sub-optimal?)

**Comment by lojjic** [comment]
@bcjordan Apologies as I shake out some cobwebs, I haven't touched this stuff in years...

As I said in that thread, the biggest problem is that IE10 drops support for .htc behaviors, so right off the bat you're stuck with a pure .js approach which is much more awkward to use -- see http://css3pie.com/documentation/pie-js/ for how to use that.

If you're ok with that, then you _might_ be able to use the stock PIE_IE9.js (from the 2.0 beta) in IE10 and have it pick up the border-image rendering. You'll probably have to hack it to ignore the check for PIE.ieDocMode.

Let me know your findings, I'm curious if it will work.
